version: '3.9'

services:
    
  zooexpoorg_postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_DB=ZooExpoOrgDB
    ports:
      - "45432:5432"
    networks:
      - shared_zooexpoorg_net
    volumes:      
      - postgres-data:/var/lib/postgresql/data
    
  zooexpoorg_rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672" 
    networks:
      - shared_zooexpoorg_net
    volumes:      
      - ./rabbitmq:/var/lib/rabbitmq

  zooexpoorg_api:
    ports:
      - "10000:80"
    networks:
      - shared_zooexpoorg_net
    env_file:
      - env.api

  zooexpoorg_worker_1:
    networks:
      - shared_zooexpoorg_net
    ports:
      - "10001:80"
    env_file:
      - env.worker

  zooexpoorg_worker_2:
    networks:
      - shared_zooexpoorg_net
    ports:
      - "10002:80"
    env_file:
      - env.worker

networks:
  shared_zooexpoorg_net:
    name: zoo_expo_org
    driver: bridge

volumes:
  postgres-data: