version: '3.9'

services:
    
  zooexpoorg_postgresql:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_DB=ZooExpoOrgDB
    ports:
      - "45432:5432"
    networks:
      - shared_zooexpoorg_net
    volumes:      
      - postgres-data:/var/lib/postgresql/data
    

  zooexpoorg_api:
    ports:
      - "10000:80"
    networks:
      - shared_zooexpoorg_net
    env_file:
      - env.api

networks:
  shared_zooexpoorg_net:
    name: zoo_expo_org
    driver: bridge

volumes:
  postgres-data: